Check if platform supports sys/auxv.h
tesseract-ocr/tesseract pull request #3717
Opened 2022-01-11 19:50 UTC by ffontaine

sys/auxv.h is not supported by uclibc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

2022-01-11 20:17 UTC, stweil requested changes
I am afraid that Tesseract will be very slow on 32 bit ARM and uClibc with this patch. Please try to find a solution which allows NEON detection with uClibc.

2022-01-11 20:25 UTC, stweil commented
Ideally uclibc should be fixed to support the missing functionality instead of compiling Tesseract code with restricted functions (this also applies to pull request #3716).

2022-01-11 20:32 UTC, ffontaine commented
Unfortunately, [uclibc-ng](https://uclibc-ng.org) won't be patched any time soon. The project is not very active and dedicated to embedded systems. If you think that this PR doesn't make sense, an other option is to disable tesseract with uclibc on buildroot side.

2022-01-11 21:20 UTC, egorpugin approved these changes

2022-01-11 21:46 UTC, stweil commented
@egorpugin, please don't merge this PR.

2022-01-25 16:05 UTC, ffontaine commented
Would it be acceptable to merge this PR?

It seems that the conclusion of https://github.com/tesseract-ocr/tesseract/pull/3716 is that function checks are better than `#ifdef` blocks.

2022-01-25 16:17 UTC, stweil commented
I see no use for ARM support without NEON because that would result in a very slow Tesseract and would prefer disabling the Tesseract build for such platforms on the buildroot side.

2022-02-19 23:23 UTC, closed without merging